### ISSUE TITLE
Label 500 Tweets from Corpus - Feb 28 2022

### ISSUE THREAD

**Issue by danielleasavage** [Isaac1o/CDFW#13]
@nayakchandan 

You should get a file from @Isaac1o with 3000 Tweets. Please label 500 of them by EOW, send back to both Issac & I.

**Comment by Isaac1o** [comment]
[https://github.com/Isaac1o/CDFW/blob/master/twitter/coyotes/data/all_queries_01.csv](url)

**Comment by nayakchandan** [comment]
underway!
